### ISSUE TITLE
部署安装后，没有“数据流处理”菜单

### ISSUE THREAD

**Issue by ccliushou** [emqx/neuron-docs#165]
File: [/zh_CN/data-processing-engine/prerequisite-setup.md](https://neugates.io/docs/zh/latest/data-processing-engine/prerequisite-setup.html)

![image](https://user-images.githubusercontent.com/10105646/195757407-9dfd8597-1af4-4f97-9b0d-598ee2326d6c.png)

![image](https://user-images.githubusercontent.com/10105646/195757500-2f90c34d-daaf-418f-a196-e7c43d2a20c6.png)

![image](https://user-images.githubusercontent.com/10105646/195757546-d6b4df67-8039-4687-b224-f69c6e9ce55b.png)

**Comment by joey8869** [comment]
Neuron 有兩個分發版本，Neuron是不帶有eKuiper流引擎，Neuron plus才會有eKuiper流引擎，你這是不帶eKuiper版本。
