### ISSUE TITLE
南向hj212-2017文档问题

### ISSUE THREAD

**Issue by hjy30312** [emqx/neuron-docs#371]
File: [/zh_CN/configuration/south-devices/hj212-2017/hj212-2017.md](https://neugates.io/docs/zh/latest/configuration/south-devices/hj212-2017/hj212-2017.html)

当 Neuron 作为客户端使用时，post 指远程设备的 TCP 端口。当 Neuron 作为服务端使用时，host 指 Neuron 在本地使用的 TCP 端口，默认为 502

post 和host应该改成port吧？

**Comment by QQDQ** [comment]
fixed
