### ISSUE TITLE
neuopc点击connect闪退

### ISSUE THREAD

**Issue by xiaomapython** [emqx/neuron-docs#410]
File: [/zh_CN/configuration/south-devices/opc-da/install.md](https://neugates.io/docs/zh/latest/configuration/south-devices/opc-da/install.html)

**Comment by xiaomapython** [comment]
日志中打印连接成功，实际软件闪退

**Comment by QQDQ** [comment]
Please put your issue to this board,THX
https://github.com/emqx/neuron/issues
