### ISSUE TITLE
“具体的插件开发教程请参考 SKD 教程。”错误

### ISSUE THREAD

**Issue by github65535** [emqx/neuron-docs#426]
File: [/zh_CN/introduction/plugin-list/plugin-list.md](https://neugates.io/docs/zh/latest/introduction/plugin-list/plugin-list.html)

"具体的插件开发教程请参考 SKD 教程。"应该是“具体的插件开发教程请参考 SDK 教程。”

**Comment by QQDQ** [comment]
fixed
