### ISSUE TITLE
emqx/neuron:latest Dashboard is broken

### ISSUE THREAD

**Issue by blownupp** [emqx/neuron-docs#429]
File: [/en_US/installation/docker.md](https://neugates.io/docs/en/latest/installation/docker.html)

When deploying a container with emqx/neuron:latest or emqx/neuron:2.7.0 as the tag you get a 404 error when navigating to x.x.x.x:7000

Changing the tag to emqx/neuron:2.6.3 remedies this, all other command line arguments with docker run being the same.

**Comment by QQDQ** [comment]
Please put your issue to this board,THX
https://github.com/emqx/neuron/issues

**Comment by QQDQ** [comment]
Please put your issue to this board,THX
https://github.com/emqx/neuron/issues
