### ISSUE TITLE
Tag的Address字段格式说明

### ISSUE THREAD

**Issue by wslin18** [emqx/neuron-docs#70]
File: [/zh_CN/getting-started/quick_start.md](https://neugates.io/docs/zh/latest/getting-started/quick_start.html

不明确添加Tag时的Address字段格式如何填写

**Comment by lixiumei123** [comment]
Please refer to the latest documentation. [quick-started](https://neugates.io/docs/en/latest/getting-started/quick_start.html#running-and-use)
