### ISSUE TITLE
南向配置

### ISSUE THREAD

**Issue by WZSHUO1207** [emqx/neuron-docs#85]
File: [/zh_CN/getting-started/quick_start.md](https://neugates.io/docs/zh/latest/getting-started/quick_start.html
按照教程操作，plugin无数据

**Comment by lixiumei123** [comment]
1. Open source versions require manual addition of a plugin, please refer to [Plugin-management](https://neugates.io/docs/en/latest/dashboard-operation/configuration.html#plugin-management).
2. The deb version is recommended for commercial versions.
